WebServer/shelfserver/shelfserver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shelfstatus.urls')),
    path('admin/', admin.site.urls),
]

WebServer/shelfserver/shelfstatus/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shelves/<int:shelf_id>', views.shelf_view, name='shelves'),
    path('tags', views.tags_view, name='tags'),
    path('product/<int:product_id>', views.product_view, name='product'),
    path('products', views.products_view, name='products'),
    path('containers', views.containers_view, name='containers'),
    path('tag/<str:tag_string>', views.tag_id, name='tag_id'),
    path('shelves/<int:shelf_id>/set_tag', views.set_last_tag, name='set_last_tag'),
    path('shelves/<int:shelf_id>/free_tag', views.free_last_tag, name='free_last_tag'),
]

WebServer/shelfserver/shelfstatus/models.py
from django.db import models
from django.utils.timezone import now
# Create your models here.
class Container(models.Model):
    name = models.CharField(max_length=256)
    weight = models.FloatField()

class Shelf(models.Model):
    name = models.CharField(max_length=256)

class Product(models.Model):
    name = models.CharField(max_length=256)

class ProductContainerRelation(models.Model):
    container = models.ForeignKey(Container, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    max_measurement = models.FloatField()

class ProductTag(models.Model):
    tag = models.CharField(max_length=64, unique=True)
    relation = models.ForeignKey(ProductContainerRelation, default=None, null=True, blank=True, on_delete=models.SET_NULL)
    active = models.BooleanField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

class ProductSpot(models.Model):
    last_tag = models.ForeignKey(ProductTag, default=None, null=True, blank=True, on_delete=models.SET_NULL)
    shelf = models.ForeignKey(Shelf, on_delete=models.CASCADE)
    position = models.IntegerField(default=-1)
    position_name = models.CharField(max_length=16, null=True, blank=True, default=None)

class ProductSpotState(models.Model):
    spot = models.ForeignKey(ProductSpot, on_delete=models.CASCADE)
    tag_present = models.ForeignKey(ProductTag, on_delete=models.CASCADE)
    measurement = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

WebServer/shelfserver/shelfstatus/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import random
from django.views.generic.list import ListView
from .models import ProductTag, Shelf, Product, Container, ProductSpot
from django.core import serializers
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import F

def shelf_view(request, shelf_id):
    shelves = Shelf.objects.all()
    shelf = Shelf.objects.get(id=shelf_id)
    # this gives you a list of dicts
    product_spots = ProductSpot.objects.filter(shelf=shelf_id).values(
        'position',
        #container_id=F('last_tag__relation__container__id'),
        #container_name=F('last_tag__relation__container__name'),
        container_weight=F('last_tag__relation__container__weight'),
        max_measurement=F('last_tag__relation__max_measurement'),
        product_id=F('last_tag__relation__product__id'),
        product_name=F('last_tag__relation__product__name'),
    )

    return render(request, "shelfstatus/shelf.html", {
        "mqtt_config" : {
            "websockets_broker" : "localhost",
            "websockets_port" : 9001,
            "client_name" : random.randrange(0, 999),
        },
        "shelf": shelf,
        "shelves": shelves,
        "activetab": "shelves",
        "product_spots_js" : json.dumps(list(product_spots), cls=DjangoJSONEncoder),
    })

def tags_view(request):
    shelves = Shelf.objects.all()
    page0 = int(request.GET.get('p', 1)) - 1
    tags_per_page = int(request.GET.get('opp', 25))
    tags = ProductTag.objects.all()[page0*tags_per_page:(page0+1)*tags_per_page]
    products = Product.objects.all()
    containers = Container.objects.all()
    return render(request, "shelfstatus/tags.html", {
        "tags" : tags,
        "products" : products,
        "containers" : containers,
        "shelves": shelves,
        "activetab": "tags",
    })




def product_view(request, product_id):
    shelves = Shelf.objects.all()
    return render(request, "shelfstatus/product.html", {
        "shelves": shelves,
        "activetab": "products",
    })

def products_view(request):
    shelves = Shelf.objects.all()
    products = Product.objects.all()
    return render(request, "shelfstatus/product.html", {
        "shelves": shelves,
        "products": products,
        "activetab": "products",
    })


def containers_view(request):
    shelves = Shelf.objects.all()
    return render(request, "shelfstatus/containers.html", {
        "shelves": shelves,
        "activetab": "containers",
    })

def tag_id(request, tag_string):
    returned_tag = ProductTag.objects.filter(tag=tag_string)
    if not returned_tag:
        data = None
    else:
        data = returned_tag.values(
            'tag',
            tag_id=F('id'),
            container_weight=F('relation__container__weight'),
            max_measurement=F('relation__max_measurement'),
            product_id=F('relation__product__id'),
            product_name=F('relation__product__name'),
        )
    return JsonResponse(list(data)[0], safe=False)

def set_last_tag(request, shelf_id):
    if(request.method == 'PUT'):
        data = json.loads(request.body)
        position = data["pos"]
        new_tag_tag = data["tag"]
        try:
            spot = ProductSpot.objects.get(shelf=int(shelf_id), position=position)
            new_tag = ProductTag.objects.get(tag=new_tag_tag)
            spot.last_tag = new_tag
            spot.save()
            tag_info = {
                'tag':new_tag.tag,
                'tag_id':new_tag.id,
                'container_weight': new_tag.relation.container.weight,
                'max_measurement': new_tag.relation.max_measurement,
                'product_id': new_tag.relation.product.id,
                'product_name': new_tag.relation.product.name,
            }
            return JsonResponse(tag_info, safe=False)
        except Exception as e:
            print(e)
            return HttpResponse(status=404)
    else:
        return HttpResponse(status=405)

def free_last_tag(request, shelf_id):
    if(request.method == 'PUT'):
        data = json.loads(request.body)
        position = data["pos"]
        try:
            spot = ProductSpot.objects.get(shelf=int(shelf_id), position=position)
            spot.last_tag = None
            spot.save()
            return HttpResponse(status=202)
        except Exception as e:
            print(e)
            return HttpResponse(status=404)
    else:
        return HttpResponse(status=405)

WebServer/shelfserver/shelfstatus/templates/shelfstatus/containers.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'shelfstatus/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">


    <!-- Custom styles for this template-->
    <link href="{% static 'shelfstatus/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'shelfstatus/css/smartshelves.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include 'shelfstatus/sidebar.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>



                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">



                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                                <img class="img-profile rounded-circle"
                                    src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-plus fa-sm text-white-50"></i> Add</a>
                    </div>
                    <div class="row">
                        <!-- Containers -->
                        <div class="col-xl-6 col-md-9 col-sm-12 col-xs-12">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Containers</h6>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="d-inline-block mr-2">
                                            <a href="#">
                                                <img class=""
                                                    src="https://dummyimage.com/64/99f/fff&text=KK">
                                            </a>
                                        </div>
                                        <div class="d-inline-block">
                                            <div><h3><a href="#">CONTAINER NAME</a></h3>
                                            </div>
                                            <div>edit | delete</div>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="d-flex">
                                        <div class="d-inline-block mr-2">
                                            <a href="#">
                                                <img class=""
                                                    src="https://dummyimage.com/64/99f/fff&text=KK">
                                            </a>
                                        </div>
                                        <div class="d-inline-block">
                                            <div><h3><a href="#">CONTAINER NAME</a></h3>
                                            </div>
                                            <div>edit | delete</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <script>

    </script>
    <!-- Bootstrap core JavaScript-->

    <script src="{% static 'shelfstatus/vendor/jquery/jquery.min.js' %}"></script>

    <script src="{% static 'shelfstatus/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'shelfstatus/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'shelfstatus/js/sb-admin-2.min.js' %}"></script>

    <script src="{% static 'shelfstatus/js/paho-mqtt.js' %}"></script>
    <!-- Page level custom scripts -->

    <script src="{% static 'shelfstatus/js/shelf.js' %}"></script>
</body>

</html>

WebServer/shelfserver/shelfstatus/templates/shelfstatus/shelf.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Dashboard</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'shelfstatus/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


  <!-- Custom styles for this template-->
  <link href="{% static 'shelfstatus/css/sb-admin-2.css' %}" rel="stylesheet">
  <link href="{% static 'shelfstatus/css/smartshelves.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

  
    {% include 'shelfstatus/sidebar.html' %}
    
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

         

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

     

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">

              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{{shelf.name}}</h1>
            <!--<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Temperature</div>
                      <div id="temperature" class="h5 mb-0 font-weight-bold text-gray-800">-</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-thermometer-half fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Pressure</div>
                      <div id="pressure" class="h5 mb-0 font-weight-bold text-gray-800">-</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-tachometer-alt fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            

            <!-- Pending Requests Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Humidity</div>
                      <div id="humidity" class="h5 mb-0 font-weight-bold text-gray-800">-</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-tint fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Content Row -->

          <div class="row">

            {% for spot in shelf.productspot_set.all %}
            <div class="col-xl-2 col-lg-4 col-sm-6 mb-4">
              <div class="card bg-light text-black shadow">
                <div class="stock-card-body">
                  <div class="stock-container">
                    {% if spot.last_tag %} 
                      <img id="spot-{{spot.position}}-bg" src="{% static 'shelfstatus/img/products/' %}{{spot.last_tag.relation.product.id}}.jpg"  class="bg">
                      <img id="spot-{{spot.position}}-level" src="{% static 'shelfstatus/img/products/' %}{{spot.last_tag.relation.product.id}}.jpg"  class="level">
                      <div style="display: none;" id="spot-{{spot.position}}-empty" class="empty bg">EMPTY</div>
                    {% else %}
                      <img style="display: none;" id="spot-{{spot.position}}-bg" src="{% static 'shelfstatus/img/products/' %}{{spot.last_tag.relation.product.id}}.jpg"  class="bg">
                      <img style="display: none;" id="spot-{{spot.position}}-level" src="{% static 'shelfstatus/img/products/' %}{{spot.last_tag.relation.product.id}}.jpg"  class="level">
                      <div class="empty bg" id="spot-{{spot.position}}-empty">EMPTY</div>
                    {% endif %}
                        <div class="menu" style="display:flex; flex-wrap:wrap; position:absolute;  overflow:hidden;  width:50%; height:50%; border-radius:50%;">
                          <a class="wheelnav-element " onclick="toggleLed({{spot.position}})"><i class="fas fa-lightbulb text-white"></i></a>
                          <a class="wheelnav-element " onclick="freeLastTag({{spot.position}})"><i class="fas fa-unlink text-white" ></i></a>
                          <a class="wheelnav-element " onclick="tare({{spot.position}})"><i class="fas fa-balance-scale text-white"></i></a>
                          <a class="wheelnav-element " onclick="calibrate({{spot.position}})"><i class="fas fa-ruler text-white" ></i></a>
                          <!--<nav class="circle-menu">      
                            <ul>
                              <li><a href="#"></a></li>
                              <li><a href="#"></a></li>
                              <li><a href="#"></a></li>
                              <li><a href="#"></a></li>
                            </ul>
                          </nav>-->
                        </div>
                      <i id="spot-{{spot.position}}-noinfo" class="fas fa-question-circle text-primary no-info"></i>
                  </div>
                  <div id="spot-{{spot.position}}-name" class="stock-name">{% if spot.last_tag %}{{spot.last_tag.relation.product.name}}{% else %}-{% endif %}</div>
                </div>
              </div>
            </div>
            {% endfor %}
           
   
          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <script>
     MQTT_BROKER_IP = "{{ mqtt_config.websockets_broker|default:"localhost" }}";
     MQTT_WEBSOCKETS_PORT = {{ mqtt_config.websockets_port|default:9001 }};
     MQTT_CLIENT_NAME = "webclient_{{ mqtt_config.client_name|default:"webclient" }}";
     MQTT_SHELF_ID = {{ shelf.id }};
     SHELF_SPOTS = {{ product_spots_js|safe }};
     CSRF_TOKEN = '{{ csrf_token }}';
     PRODUCT_IMAGES_DIR = '{% static 'shelfstatus/img/products/' %}'
  </script>
  <!-- Bootstrap core JavaScript-->
  
  <script src="{% static 'shelfstatus/vendor/jquery/jquery.min.js' %}"></script>
  
  <script src="{% static 'shelfstatus/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'shelfstatus/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'shelfstatus/js/sb-admin-2.min.js' %}"></script>

  <script src="{% static 'shelfstatus/js/paho-mqtt.js' %}"></script>
  <!-- Page level custom scripts -->

  <script src="{% static 'shelfstatus/js/shelf.js' %}"></script>
</body>

</html>

WebServer/shelfserver/shelfstatus/templates/shelfstatus/sidebar.html
<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-box-open"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SHLV<sup>5</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">



      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Shelves
      </div>
      {% for sh in shelves %}
      <!-- Nav Item - Shelf -->
      <li class="nav-item {% if sh.id == shelf.id %}active{%endif%}">
        <a class="nav-link" href="{% url 'shelves' sh.id %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>{{ sh.name }}</span></a>
      </li>
      {% endfor %}

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Configuration
      </div>

      <!-- Nav Item - Pages Collapse Menu
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="login.html">Login</a>
            <a class="collapse-item" href="register.html">Register</a>
            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="404.html">404 Page</a>
            <a class="collapse-item" href="blank.html">Blank Page</a>
          </div>
        </div>
      </li>
      -->
      <!-- Nav Item - Tags -->
      <li class="nav-item {% if activetab == 'tags' %}active{%endif%}">
        <a class="nav-link" href="{% url 'tags' %}">
          <i class="fas fa-fw fa-tags"></i>
          <span>Tags</span></a>
      </li>

      <!-- Nav Item - Products -->
      <li class="nav-item {% if activetab == 'products' %}active{%endif%}">
        <a class="nav-link" href="{% url 'products' %}">
          <i class="fas fa-fw fa-th"></i>
          <span>Products</span></a>
      </li>
      <!-- Nav Item - Containers -->
      <li class="nav-item {% if activetab == 'containers' %}active{%endif%}">
        <a class="nav-link" href="{% url 'containers' %}">
          <i class="fas fa-fw fa-box"></i>
          <span>Containers</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->